### ISSUE TITLE
Openning a vault is slow

### ISSUE THREAD

**Issue by julianfairfax** [aivanovski/kpassnotes#133]
It seems that when you open a vault, i.e. enter your password and click open, the opening process is quite slow.

**Comment by aivanovski** [comment]
Yes, that is true. App checks for new changes each time during the opening process. This check may proceed into a network call if the database is located in WebDav or Git.

@julianfairfax Which one do you use (WebDav or Git)? If you are using Git, then it may take some time. Because app does `fetch` and then `pull` on the repository while opening. They aren't fast on Android devices and may depend on the size of the repository.

Actually, It's actually the next thing I'm going to fix in the app. The locally cached file could be opened and then app may check for new changes.

**Comment by aivanovski** [comment]
Could you please provide additional information?

1 - How did you set up the file in KPassNotes? I suppose you open it, did you use KPassNotes as a file picker or another app? What was the another app if you used it?
2 - Where the file is really stored?
3 - What is the size of the file?

@julianfairfax

**Comment by aivanovski** [comment]
The built-in file picker should be as fast as it can be. I have 22 kB database with a couple of binary files inside it. It is opened almost instantly on my Google Pixel 6.

I'm a bit confuse, It should work fast in your case. I don't have any idea what can be the reason. What Android Device do you use (please specify also version of Android OS)? Are you able to provide the video?

**Comment by aivanovski** [comment]
It can be caused by the number of key transformation rounds.
For example with the settings below is opened almost instantly in KPassNotes and on laptop:
![Screenshot from 2023-06-03 17-06-02](https://github.com/aivanovski/kpassnotes/assets/1074496/34bd1b42-7f59-4a9b-9818-931fd8204ac5)

But with another settings it takes more than 1 minute in KPassNotes to open and at least 5-7 seconds on the laptop:
![Screenshot from 2023-06-03 17-07-13](https://github.com/aivanovski/kpassnotes/assets/1074496/15a9ee41-cf04-4ea6-86d5-596ee9c38a80)

You may check it or change it in KeePassXC on the desktop

**Comment by aivanovski** [comment]
> Using AES-KDF (KDBX 4) with 1000000 transform rounds (which it resets too after that warning for 6000) does make the opening of the file faster. Is it less secure than Argon2d (KDBX 4)?
I don't understand KeePass well enough to answer that question :) But as I understand, transformation rounds are not so important as a strong master password.

I'm not sure what you mean by "other", but some other apps, for example KeePassDX, use C/C++ code in order to work with KeePass database. KPassNotes uses [kotpass](https://github.com/keemobile/kotpass) library for that, it is written in Kotlin. I haven't done any benchmarks, but I'm pretty sure that C/C++ should work much faster in that case.
